MainInterface:

<MainInterface>:
    ScreenManager:
        id: sm
        size: root.width, root.height
        Screen:
            name: "background_1"
            Image:
                source: "Background_1.png"
        Screen:
            name: "background_2"
            Image:
                source: "Background_2.png"
        Screen:
            name: "background_3"
            Image:
                source: "Background_3.png"